name: Test and Lint
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64.5
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Clean
        run: go clean -modcache -v

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Test
        run: go test ./...

      - name: Clean
        run: go clean -modcache -v
